version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8000
      CLIENT_ORIGIN: http://localhost:5173
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_HOST: backend
        VITE_BACKEND_PORT: 8000
    ports:
      - "5173:80"
    depends_on:
      - backend
